export {
  clearAccessToken,
  ensurePassengerAccessToken as ensureAccessToken,
  getAccessToken,
} from '../infrastructure/auth/passengerAuthSession'

export { ApiError } from '../infrastructure/http/httpClient'

export type {
  AdminKeyInfo,
  AdminQrSaleAudit,
  AdminSessionUser,
  CurrentUser,
  DriverQrIssueResult,
  DriverQrRedeemResult,
  PassengerQrIssueResult,
  DriverSessionUser,
  PaginatedResult,
  PaginationParams,
  RidePointOverride,
} from '../infrastructure/api/contracts'

export {
  createAdminKey,
  createDriver,
  createMapMark,
  createServiceZone,
  deleteAdminKey,
  deleteDriver,
  deleteMapMark,
  deleteServiceZone,
  getAdminSession,
  listAdminKeys,
  listMapMarks,
  listAdminQrSales,
  listAdminRequests,
  listDrivers,
  loginAdminByKey,
  logoutAdminSession,
  revokeAdminKey,
  rotateAdminKey,
  rotateDriverKey,
  updateAdminKey,
  updateDriver,
  updatePricing,
  updateServiceZone,
  uploadMapMarkPhoto,
  uploadDriverPhoto,
  assignDriverBulk,
  patchAdminRideRoute,
} from '../infrastructure/api/adminApi'

export {
  applyDriverPointAction,
  rateRideAsDriver,
  getDriverCabinet,
  claimDriverRide,
  getDriverMapData,
  bootstrapDriverAccess,
  getDriverSession,
  issueDriverQrSale,
  loginDriverByKey,
  logoutDriverSession,
  notifyPickupChange,
  redeemPassengerQrSale,
  resetDriverRidePickup,
  sendDriverLocation,
  setDriverOnlineStatus,
  setDriverRideStatus,
  updateDriverRidePickup,
  updateDriverRideRoute,
} from '../infrastructure/api/driverApi'

export {
  confirmPickup,
  rateRideAsPassenger,
  completeOnboarding,
  createRequest,
  deleteRequest,
  getCurrentUser,
  getPricing,
  getRideQuote,
  getRequestById,
  getUserCabinet,
  listPublicMapMarks,
  listGroupSuggestions,
  listMyRequests,
  listServiceZones,
  purchasePointsByCard,
  issuePassengerQrSale,
  updateCurrentUserLanguage,
  updateRequest,
} from '../infrastructure/api/passengerApi'

export {
  getAdminUnreadCount,
  getDriverUnreadCount,
  getPassengerUnreadCount,
  listAdminNotifications,
  listDriverNotifications,
  listPassengerNotifications,
  markAdminNotificationRead,
  markAllAdminNotificationsRead,
  markAllDriverNotificationsRead,
  markAllPassengerNotificationsRead,
  markDriverNotificationRead,
  markPassengerNotificationRead,
  sendAdminNotification,
} from '../infrastructure/api/notificationsApi'

export type { AdminSendNotificationPayload, AdminSendNotificationResult } from '../infrastructure/api/notificationsApi'

export {
  approveDriverApplication,
  getDriverApplication,
  getDriverCabinetEnterUrl,
  getDriverRegistrationForm,
  getDriverRegistrationSettings,
  getMyDriverApplication,
  listDriverApplications,
  rejectDriverApplication,
  submitDriverApplication,
  updateDriverRegistrationSettings,
  uploadDriverApplicationFile,
} from '../infrastructure/api/driverRegistrationApi'
